//this script contains cutscene 6's script
function script_cutscene_6()
{
	myText[0] = "{Welcome, Ryu Hayabusa.\n Sorry if I startled\n you.{"
	myText[1] = "{We are from the CIA\n Special Auxiliary unit.\n My name's Foster.{"
	myText[2] = "{...{"
	myText[3] = "{Getting right to the\n point...{"
	myText[4] = "{Wait. I want to know\n why you killed Smith?{"
	myText[5] = "{We didn't kill him.\n But we'll fill you in\n on what we do know.{"
	myText[6] = "{In the upper reaches of\n the Amazon, some\n ancient ruins were\n discovered."
	myText[7] = "{It seems the temple was\n built more than 2000\n years ago."
	myText[8] = "{The discoverer was Dr.\n Smith, who studied the\n ruins for some time."
	myText[9] = "{But one day, he\n suddenly sealed off the\n ruins."
	myText[10] = "{And ever since then\n no one has gone close."
	myText[11] = "{Later, however, a man\n moved in and took over\n the ruins. His name is\n Guardia de Mieux."
	myText[12] = "{He calls himself\n the Jaquio."
	myText[13] = "{According to our\n records, it seems that"
	myText[14] = "{the temple is not where\n gods are worshipped but\n was built to imprison\n the body of the demon."
	myText[15] = "{Therefore, evil spirits\n are supposed to be held\n in the statue you have."
	myText[16] = "{Dr. Smith probably\n already knew that."
	myText[17] = "{He was probably killed\n by someone working for\n the Jaquio."
	myText[18] = "{...{"
	myText[19] = "{When a black moon\n shines, Light and Dark\n break apart, the King\n of Darkness howls.{"
	myText[20] = "{These were the last\n words written on the\n stone tablet."
	myText[21] = "{If someone brings the\n demon back to life, he\n will gain incredible\n power..."
	myText[22] = "{Enough to control the\n entire world.{"
	myText[23] = "{So you know about that?{"
	myText[24] = "{The woman who shot you\n in the bar was one of\n our agents.{"
	myText[25] = "{They are after you."
	myText[26] = "{Use this and go to\n their headquarters.\n Get the demon statue\n back from them."
	myText[27] = "{Of course, you will be\n paid for the work.{"
	myText[28] = "{And if I say no?{"
	myText[29] = "{You know the answer to\n that.{"
}